### ISSUE TITLE
Cross org group delegation clarifications

### ISSUE THREAD

**Issue by harshitk-arista** [openconfig/ovgs#17]
Context: We’d like to allow an org in ovgs to be able to issue vouchers for serials owned by another org, for the same vendor.  Notably, the solution must not require the vendor to take an action on their end. If the two orgs (each with their own hierarchy) agree, they ought to be able to delegate ownership of a serial.

After some initial discussions, the mechanism we’ve chosen to do this is to allow the _delegator_ (owner of a device) to assign roles to users from the _delegatee’s_ (to whom the permissions are being accorded) org. Why? Given the permission mechanism in ovgs is built around groups, this seems like the obvious choice, because it allows the delagatee to re-use all the existing methods we have around permissions in ovgs authz. Moreover, given the hierarchical structure of groups (and thus permissions), the right set of permissions needed for this cross org delegation naturally falls out.

This issue is to discuss and close down on 2 open points. Specifically - 

1. How do device owners signal whether a group in their org hierarchy can be delegated to users in a different org i.e. _AddUserRole_ can be invoked for users whose _org_id_ does not match the caller's _org_id_. We have 4 options -

    a.) Default allow _AddUserRole_ to assign users from a different org a role over the delegator’s groups. Specifying an org_id which is different from the caller’s org implies consent

    b.) Allow a per org setting (only invokable by a user with ADMIN privileges over the root group) that will allow the delegator to delegate any group in their hierarchy

    c.) Allow a per group setting (only invokable by a user with ADMIN privileges over that root group) which allows the delegator to delegate that specific group (any sub groups created under that group are auto delegated too, given the hierarchical nature of permissions)

    d.) Allow a per group (X) + per org (A) knob. The delegator MUST specify the org and the group to which they intend to delegate the group, after which they’re allowed to invoke AddUserRole for user from org A where group = X

   Based on a prior discussion, option D is too flexible and we don’t want to go in that direction.

   Option A is too permissive. Cross org permissions should be opt in, not opt out. Isolating each org/tenant by default and providing a way for       tenants who wish to share state amongst each other would be the right thing for any authz system imho.

    As for option B and option C -  Group are the primary construct in ovgs authz  - users get assigned roles on a group, which gives them a certain set of privileges to the devices and certs assigned to the group (and the subtree rooted at that group). Allowing for this to be done at the group level seems natural then. Moreover, all the groups can be delegated easily by option C, by setting group = root-group, so option B really becomes a specific case of option C.

   I  think we should go with option C, unless there are other arguments for doing something different.

2. Should we allow delegation for the root group?

    The argument for not doing this is the following - Any new devices purchased by the delegator show up in the root group by default, so they    will automatically be available to the delegatee to request ownership vouchers for. Imho, this could be a possible footgun.

    If we disallow this, the delegator MUST choose which set of serials to move to the delegated group

**Comment by harshitk-arista** [comment]
@heas@google.com

**Comment by haussli** [comment]
Hey Harshit.
I would choose 1a.  No change is required to the proto nor other existing implementations, and it fits my philosophy of flexibility.  1b would be an option that could be completely "hidden" in the implementation and so would be nearly equivalent; your implementation would just return a permission denied error.

Another option, which I am not fond of, but does not alter the proto messages, is to introduce a specific version of the AddUserRole RPC for adding users whose org-id does not match that of the root-group.  I'd still choose 1a.

As for 2, I would allow it.  Besides not creating a special case, it would would allow a company to delegate management of their hierarchy to a contractor.  For example, a leasing company or a company that contracts their device management.

However, I am all for removing safety labels from wood chippers and letting nature take its course.  You should also ask other's opinions.  @morrowc ?

**Comment by morrowc** [comment]
1a seems ok to me!

**Comment by JonLundstrom** [comment]
Hi Folks,
	As an implementor, it was comforting to discover this issue covers many of our internal discussions on the subject. 
	To cover the easiest topic first, our opinion on 2 is that delegation of the root group/org should not be allowed. Our position is exactly as is mentioned by Harshit, that new devices are automatically added to the root group, before being assigned by the owner to a sub-group, and as such, any delegation of the root group/org opens the owner to a security concern. We are in favour of only delegating the sub-group, and believe the extra administration task of assigning the devices to the sub-group by the owner is minimal, and adds an auditable step for logging and security purposes. 
 To Haussli’s comment about #2, couldn’t the contractor use case be easily covered by the owner creating and delegating a sub-group to the contractor, and assigning all the devices to that sub-group. Admittedly this is slightly more work for the owner, but again, adds an auditable security step each time new devices are purchased and assigned to a sub-group, and allows for additional contractors to be added with their own sub-groups in the future. 
	With respect to the options for #1, we see options C or D as preferable, as they provide tighter security controls to the delegator to limit the scope and management of delegatees. We see Option D as a minor variation from Option C but with the addition of explicit setting of the root-group/org as well as the sub-group per delegatee, versus the implicit definition of the root group/org per delegatee based on which root group/org the sub-group is in. In a situation where the same delegatee user was delegated to by more than one delegator with different root groups/orgs, we see there may be accounting/tracking value in the explicit definition of root group/org + sub-group per user of Option D. 

Harshit, can you please elaborate on your comment that Option D is too flexible?

**Comment by haussli** [comment]
Find below a summary of the call from this morning and proposals for the changes.

Harshi:
Concerns are:
1) In a multi-tenant environment, we want individual orgs to normally be isolated.  They should have to opt-in to allowing delegations.

2) Do we want delegation for the root group?  Then all new serials are automatically accessible.

And from the previous comment in this issue:
3) A user-Z in org-X, to whom a group is delegated in org-Y, should not be allowed to call AddUserRole, on the group or its children, for users outside of org-X.

4) GetUserRole does not take the group_id as an input parameter, so it's permissions are not clear. We think a delegated user from org X shuld not be allowed to invoke GetUserRole on users of org Y.

Jonathan:
Concerns are:
5) Delegation seems dangerous.  Want more explicit acceptance of delegation feature.
6) If a delegatee can add other users to the delegated group or its children; possibly need another UserRole type that is not allowed to call AddUserRole.
7) Who vets the delegatee?  user@foo.org creates an account on the vendor-portal with org_id foo.  How does a delegator vet user@foo.org?  The vendor should not be involved.  Should there be an external process?

No other concerns were raised.

--------------------

All agree about harshi's concerns 1 & 2 and  that 1 & 5 are essentially the same.

Regarding 1 (and 5):
It was agreed that a field should be added that indicates that a given group accepts delegation (users from a foreign org_id).  The field should be affected by a new RPC, so that it can affect the root group, and GetGroup() should return the field.

```
Add new field:
message GetGroupResponse {
  // Permit foreign users; users whose org_id does not match rootgroup:group_id.
  // The default value is false, disabled.
  // AddUserRole() for a foreign user to a group without delegation enabled returns 
  bool enable_delegation = 7;
}

Add new constraint:
// AddUserRole ...
// Returns INVALID_ARGUMENT if org_id does not equal rootgroup:group_id and enable_delegation is false.

Add new RPC and its messages:
// enable_delegation controls where a group can be delegated to foreign users.
// Roles with permission to invoke this = ADMIN
message SetGroupDelegationRequest {
  // Group id
  string group_id = 1;
  // Permit foreign users; users whose org_id does not match rootgroup:group_id.
  // Inherited by child groups.
  bool enable_delegation = 2; 
}
message SetGroupDelegationResponse {
}
 // SetGroupDelegation enables or disables delegation on the named group.
 // group_id is the required and must exist.
  // Errors will be returned:
  // INVALID_ARGUMENT if any field is empty.
  // NOT_FOUND if the group doesn't exist, as specified in the request.
  // PERMISSION_DENIED if the user doesn't have access to the group or RPC.
  // Roles with permission to invoke this = ADMIN
  rpc SetGroupDelegation(SetGroupDelegationRequest) returns (SetGroupDelegationResponse);
```

Regarding 2:
Root group delegation allows a company, such as a leasing company, to hire a third party to manage its OVGS tree.  Allowing the third party to perform all OVGS functions, including further delegations.

This was accepted, as long as # 1 was addressed.


Regarding 3 and 6:
I believe that we decided these were similar and could be addressed together.

It was discussed, but not yet agreed, that a solution to this might also replace the solution to # 1 & 5.  The proposal is to add a repeating string field to the group structure (and an RPC to manipulate it) that contains either a wildcard ("*", ie: "allow everything") or a list of possible org_ids that foreign users must belong to be allowed in the group.


Regarding 4:
It was agreed to limit access of GetUserRole to the same org_id.

```
  Add constraint:
  // GetUserRole returns the roles the user is assigned in the group.
  // ...
  // PERMISSION_DENIED if user's org_id does not match that of the username in the GetUserRoleRequest.
```


Regarding 7:
Morrow questioned whether this is necessary, given that user@foo.org must tell the delegator what their username and org_id is for the AddUserRole(), and that communication is presumably done in some manner that implicitly authenticates the tuple.  That combined with the # 3 and 6 fix, might address this vetting?

However, Harshi would consider implementing a new RPC to address Jonathan's vetting concern.

I am fairly certain that I missed something in this part of the conversation and may not have captured the suggestions correctly.  I definitely missed what the vetting RPC might be.  Please help fill in the blanks.

------------------

Remaining questions:
Regarding # 1 and 5:
- What happens if a user's org_id changes?
- Should enable_delegation inherit from its parent group at the time of creation?
- What happens if enable_delegation is disabled after a group has foreign users?

Regarding # 3 and 6:
- Does the proposal address the concerns?
- What happens to users already in the group if the list changes?
- Does it replace the proposed solution to # 1?

Please comment with suggestions or corrections.  We can meet again on Dec. 9 at the same time, if necessary.

**Comment by haussli** [comment]
> > What happens if a user's org_id changes?
> Since each user is a triplet (username, org_id, group_id), if a user's org-id changes, it will be a completely different user.

And...?  Should the old user be automatically purged from any delegations, or anywhere its org_id does not match?


Dec 9 or 10 seems too short of a warning for a next call.  I can not host on 16. Dec.  Might have to reschedule, but I propose 17. December 2025 at 10:00 CST. That is 21:30 IST, 0600 HST, 1000 CST, 1600z. The meet link is https://meet.google.com/tgr-dnxr-uik .

**Comment by mayank-singla001** [comment]
Sure, makes sense. Thanks!

**Comment by haussli** [comment]
Notes from today's meeting.

Remaining questions from previous meeting:
> Regarding # 1 and 5:
>
>     What happens if a user's org_id changes?
>     Should enable_delegation inherit from its parent group at the time of creation?
>     What happens if enable_delegation is disabled after a group has foreign users?

Everyone agreed that the proposed solution to #3 & 6 would also resolve #1 & 5.

> Regarding # 3 and 6:
>
>     Does the proposal address the concerns?
>     What happens to users already in the group if the list changes?
>     Does it replace the proposed solution to # 1?

Another solution was proposed (Sudheer G, I think):
owner-org uses AddSerial() to place a serial in a group owned by org-delegatee(s).  This would still require that the destination group have some authorization mechanism that allow owner-org to read (audit) and write (add/remove) the destination-group.  Doubtful that this improves the problem space, we moved onto discussing the previous proposal.

That proposal is to add a repeating string field to the group structure (and RPC(s) to manipulate it) that contains either a wildcard ("*", ie: "allow everything") or a list of possible org_ids that foreign users must belong to be allowed in the group.

No one disagreed that the solution addresses the issues #1, 3, 5, 6.

If the org list changes, users whose org is no longer a member should be expunged from the hierarchy rooted at the group whose org list changed.

An additional constraint was mentioned, which was agreed: third party users should not have access to a group's org_list (GetGroup() should omit the field) nor allow them to change the list (return permission denied).

It was asked if there a permissions issue resolving delegated user in a sub-group if the user has different perms on the sub-group than the parent (or root of the delegation).  It is believed that it would not, if the server walks up the hierarchy to resolve the delegate-org-list.


Thanks.  If any other concerns arise while folks consider these solutions or if I made an error in the notes, please raise those here.

**Comment by acevedohulk** [comment]
Hello team,

Following our discussion on Wednesday, Nokia agrees with the proposed model. Please find our key takeaways below.

Effect on earlier open questions
•	#1 & #5 (org_id change & enable_delegation inheritance) – resolved by the org_list logic and background cleanup.
•	#3 & #6 (list changes & impact on existing members) – addressed by the same cleanup process; users whose org is no longer allowed are automatically removed from the hierarchy rooted at the affected group.
•	The solution also satisfies the “owner-org uses AddSerial()” alternative, making it unnecessary.

Below is the approach we will use for the model

1.Group-level org-list field
        •	A repeating string field (the “org_list”) will be added to the group data model.
        •	It can contain either a wildcard (“*”) to allow any org, or an explicit list of org-ids whose users are permitted to join the group.
        •	RPCs will be provided to read/write this field (subject to permissions).

2.Permission rules for the org-list
        •	Third-party users cannot read the org_list (GetGroup omits the field).
        •	Third-party users cannot modify the org_list (permission-denied response).

3.Adding third-party users
        •	Third party users must be registered with the vendor before AddUserRole API can me utilized. 
        •	Users are added only via AddUserRole.
        •	The service checks that the user’s current org_id appears in the target group’s org_list before allowing the addition.
        •	Third-party users cannot add additional third-party users.
        
4.Inheritance
        •	The org_list is inherited by sub-groups from root group.
        •	Delegated users in sub-groups inherit the same org-list checks as the parent group; permission resolution walks up the hierarchy.

5.Handling org_id changes
    •	A background cleanup process runs when a user’s org_id changes: 
          •    It removes the user from any groups where they are now a third-party member whose org is not on that group’s org_list.
          •	If the org of a user is changed and the user’s new org is not in the group’s org_list, that user will be removed from the org.

**Comment by mayank-singla001** [comment]
> " USER_ROLE_SUPERADMIN = 5;" ? I thought that we agreed that this is unnecessary. I see that you wrote on Dec 8 in the issue
>
> 
> Should it not just compare the caller's org_id to that of the root of the hierarchy for delegation? Also, you're changing the behavior of USER_ROLE_ADMIN.

I think the reason for introducing this was that we don't want all existing ADMINs to get the permissions for delegation. It was previously suggested to only allow ADMINs of the root group to call the new RPC. But instead of adding this check, introducing a new role makes more sense (name of the role can be discussed further) to call this new RPC. The ADMIN still have all the permissions except for delegation. We can discuss upon the role name, maybe `DELEGATOR_ADMIN`?
We ideally want to have a new `DELEGATOR` role, and want to give CVaaS users by default `ADMIN + DELEGATOR` role, but the current proto of OVGS doesn't allow union of roles and is more of hierarchy based, so we need a new higher role which will be assigned by default to the CVaaS users having R&W permissions to the OVGS module.
 
> > // AddGroupDelegatedOrg adds the delegated org for the given group_id.
> > s/for/to/
> 
> > // RemoveGroupDelegatedOrg removes the delegated org for the given group_id.
> > s/for/from/
> 
> > // INVALID_ARGUMENT if any field is empty,
> > //   or, the users list has any user from the org to be deleted
> 
> I thought that the behavior was going to be just delete those users?

We had that before, but we want to prevent any accidental deletion of users by invoking this, similar to `DeleteGroup` RPC. Also, we don't want an RPC to change the behavior defined by any other RPC. So we should first delete all the delegated users using `DeleteUserRole` explicitly and then remove the delegated org.

> > ```
> > org_id can be * as a wildcard to allow any org
> > ```
> 
> should be in the comments and docs.

Yes, will do that in the proto changes.

**Comment by haussli** [comment]
Sorry, I disagree.  Entirely because, unless i am mistaken, these are not what everyone agreed in the previous discussions.  I will have to re-read the discussion to confirm for myself.

But, if you wish to change course, the other implementers must be consulted again.

**Comment by mayank-singla001** [comment]
Okay, then, if we don't want the new role, should all ADMINs of the original org be allowed to change the `delegated_org_ids` list, i.e., call the new RPCs, if they have permissions over a group?

**Comment by haussli** [comment]
> From the past discussions, we had only `ADMINs` of the root group of the original group should be allowed to change the `delegated_org_ids`. If that seems okay, can we conclude this discussion, and I will create the proto changes? [@haussli](https://github.com/haussli)

To be specific, my recollection is "an ADMIN" (any admin) whose organization matches that of the root group.

**Comment by haussli** [comment]
I think that I want to rewind to Nokia's summary (https://github.com/openconfig/ovgs/issues/17#issuecomment-3682638352).  I think that captured what we had agreed on the last call.  I will make a few corrections in-line that I think were part agreed/understood - and try to fix github's mangled quoting for readability.
 
> Following your feedback, I’ve updated the previous wording.
> 
> 1.Group-level org-list field 
> • A repeating string field (the “org_list”) will be added to the group data model.
> • It can contain either a wildcard (“*”) to allow any org, or an explicit list of org-ids whose users are permitted to join the group. _**
> • RPC GetGroup() will be utilized to read/write this field (subject to permissions).**_

Getgroup will only read the field; new RPCs, such as the ones Arista has suggested (*GroupDelegatedOrg).

> 2.Permission rules for the org-list 
> • Third-party users cannot read the org_list (GetGroup omits the field). **
> • Third-party users cannot modify the org_list (permission-denied response). __Optional._**--From our perspective, it serves as an added security layer to preserve the hierarchy_ ``

To be specific, my recollection is "an ADMIN" (any admin) whose organization matches that of the root group.  But this complicates the scenario where the owner delegates their root group to a contractor.

> 3.Adding third-party users 
> • Third party users must be registered with the vendor before AddUserRole API can be utilized. 
> • Users are added only via AddUserRole. 
> • The service checks that the user’s current org_id appears in the target group’s org_list before allowing the addition. 
> • Third-party users cannot add additional third-party users.

> 4.Inheritance 
> • The org_list is inherited by sub-groups from root group. 
> • Delegated users in sub-groups inherit the same org-list checks as the parent group; permission resolution walks up the hierarchy.

> 5.Handling org_id changes 
> • A background cleanup process runs when a user’s org_id changes: 
> • **It removes the user from any _group/hierarchy_ where their new org_id is not the owner org or is not in the org_list.** _**

I think that we agreed that their membership should be removed, regardless of their new org_id.  Otherwise, there is potential for unintended latent permissions.

> • If the org_list changes, member users whose org is no longer in the org_list will be removed.**_

Note: there was no special language for "*"; so users matching "!*@<root_group_id>" should be removed.

---------------------------------------------
Questions that followed were:
A)  did we agree to the inheritance described in 4?  I suspect that the disagreement is really a difference in interpretation of the text and that the intention is simply that the inheritance follows the same method of walking back up the tree to resolve permissions.

Suggestions/issue that we can choose to address or not:
B) Arista has suggested a new USER_ROLE that is required for the *GroupDelegatedOrg RPCs, which was not part of the suggestions in the last call.

If this change is to be considered, all must agree.

C) The permissions required to manage the org_list and user list create an obstruction to an owner hiring another company to manage their ovgs hierarchy.

**Comment by mayank-singla001** [comment]
> To be specific, my recollection is "an ADMIN" (any admin) whose organization matches that of the root group. But this complicates the scenario where the owner delegates their root group to a contractor.

Yes, that is why we discussed only `ADMINs` of the root group of the original org, and not just any `ADMIN`. Also, if the owner delegates their root group to a contractor, the contractor's org will still be different from that of the owner, and they will not be able to delegate further.

**Comment by mayank-singla001** [comment]
Hi everyone, please review the raised PR for the proto changes on this
https://github.com/openconfig/ovgs/pull/38

**Comment by mayank-singla001** [comment]
Hi, the feature implementation is complete, and the functionality is now ready to use. I think we can close this issue now @haussli
